require("7empest.plugins.whichkey")
require("7empest.plugins.treesitter")
require("7empest.plugins.lsp")
require("7empest.plugins.colorscheme")
require("7empest.plugins.null-ls")
require("7empest.plugins.nvim-cmp")
require("7empest.plugins.telescope")
-- require("7empest.plugins.lazygit")
require("7empest.plugins.comment")
require("7empest.plugins.lualine")
